# Generated by Django 4.1 on 2023-01-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FinalApp", "0003_alter_alarm_user_alter_result_webpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="FinalApp.user"
            ),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="webpage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarms",
                to="FinalApp.webpage",
            ),
        ),
    ]
