# Generated by Django 4.1 on 2023-01-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FinalApp", "0004_alter_alarm_user_alter_alarm_webpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarm",
            name="user",
        ),
        migrations.AlterField(
            model_name="alarm",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webpages",
                to="FinalApp.user",
            ),
        ),
    ]
