# Generated by Django 4.1 on 2023-01-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FinalApp", "0005_remove_alarm_user_alter_alarm_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarm",
            name="name",
        ),
    ]
